## Data Wrangling

### **Gathering Data**

In [198]:
import pandas as pd

In [199]:
customer_df = pd.read_csv('https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/refs/heads/main/DicodingCollection/customers.csv')

customer_df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
0,1,fulan 1,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia
1,2,fulan 2,Prefer not to say,69,8327 Kirlin SummitApt. 461,8223,New Zacharyfort,South Australia,Australia
2,3,fulan 3,Prefer not to say,59,269 Gemma SummitSuite 109,5661,Aliburgh,Australian Capital Territory,Australia
3,4,fulan 4,Prefer not to say,67,743 Bailey GroveSuite 141,1729,South Justinhaven,Queensland,Australia
4,5,fulan 5,Prefer not to say,30,48 Hyatt ManorSuite 375,4032,Griffithsshire,Queensland,Australia

In [200]:
order_df = pd.read_csv('https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/refs/heads/main/DicodingCollection/orders.csv');

order_df.head()

   order_id  customer_id  payment order_date delivery_date
0         1           64    30811  2021-8-30    2021-09-24
1         2          473    50490   2021-2-3    2021-02-13
2         3          774    46763  2021-10-8    2021-11-03
3         4          433    39782   2021-5-6    2021-05-19
4         5          441    14719  2021-3-23    2021-03-24

In [201]:
product_df = pd.read_csv('https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/refs/heads/main/DicodingCollection/products.csv')

product_df.head()

,product_id,product_type,product_name,size,colour,price,quantity,description
0,0,Shirt,Oxford Cloth,XS,red,114,66,"A red coloured, XS sized, Oxford Cloth Shirt"
1,1,Shirt,Oxford Cloth,S,red,114,53,"A red coloured, S sized, Oxford Cloth Shirt"
2,2,Shirt,Oxford Cloth,M,red,114,54,"A red coloured, M sized, Oxford Cloth Shirt"
3,3,Shirt,Oxford Cloth,L,red,114,69,"A red coloured, L sized, Oxford Cloth Shirt"
4,4,Shirt,Oxford Cloth,XL,red,114,47,"A red coloured, XL sized, Oxford Cloth Shirt"

In [202]:
sales_df = pd.read_csv('https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/refs/heads/main/DicodingCollection/sales.csv')

sales_df.head()

   sales_id  order_id  product_id  price_per_unit  quantity  total_price
0         0         1         218             106         2        212.0
1         1         1         481             118         1        118.0
2         2         1           2              96         3        288.0
3         3         1        1002             106         2        212.0
4         4         1         691             113         3        339.0

**Assessing Data and Cleaning Data**
### Menilai Customer_df

In [203]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1007 non-null   int64
 1   customer_name  1007 non-null   object
 2   gender         989 non-null    object
 3   age            1007 non-null   int64
 4   home_address   1007 non-null   object
 5   zip_code       1007 non-null   int64
 6   city           1007 non-null   object
 7   state          1007 non-null   object
 8   country        1007 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.9+ KB

In [204]:
customer_df.isna().sum()

customer_id       0
customer_name     0
gender           18
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
dtype: int64

In [205]:
print("Jumlah duplikasi : ", customer_df.duplicated().sum())

Jumlah duplikasi :  6

In [206]:
customer_df.describe()

       customer_id          age     zip_code
count  1007.000000  1007.000000  1007.000000
mean    501.726912    50.929494  5012.538232
std     288.673238    30.516299  2885.836112
min       1.000000    20.000000     2.000000
25%     252.500000    34.000000  2403.500000
50%     502.000000    50.000000  5087.000000
75%     751.500000    65.000000  7493.500000
max    1000.000000   700.000000  9998.000000

#### Hasil Penilaian / Assesment customer_df
Masalah yang ada pada **customer_df**

*   18 data pada kolom gender yang NULL / Kosong
*   6 buah data duplikasi
*   kolom umur yang tidak akurat, dimana umur maksimal 700

### Membersihkan customer_df

#### Menghapus data yang duplikat

In [207]:
# Menghapus data yang duplikat
customer_df.drop_duplicates(inplace=True)

print('Jumlah duplikasi :', customer_df.duplicated().sum())

Jumlah duplikasi : 0

#### Mengisi Missing Value

In [208]:
# Mengambil data yang memiliki missing value
customer_df[customer_df.gender.isna()]

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
38,39,fulan 39,NaN,80,7440 Cameron Estate DrSuite 628,4622,North Victoriachester,Northern Territory,Australia
167,168,fulan 168,NaN,27,2781 Berge MallSuite 452,1975,North Leoburgh,Western Australia,Australia
322,322,fulan 322,NaN,30,593 Becker CircleApt. 333,1640,Jacobiview,Western Australia,Australia
393,393,fulan 393,NaN,34,5158 Levi HillSuite 531,1474,Johnsburgh,Queensland,Australia
442,442,fulan 442,NaN,26,5157 Feil RoadApt. 633,7249,Port Chloe,New South Wales,Australia
722,720,fulan 720,NaN,40,31 Jordan ParadeApt. 400,1380,West Henry,South Australia,Australia
745,743,fulan 743,NaN,57,09 Christopher StreetSuite 967,6226,Lake Lukemouth,Western Australia,Australia
773,771,fulan 771,NaN,74,7367 Wright JunctionApt. 773,8882,Kuhntown,Victoria,Australia
798,795,fulan 795,NaN,49,487 Summer MewsApt. 874,1712,East Hayden,Australian Capital Territory,Australia
801,798,fulan 798,NaN,56,27 Aiden KnollApt. 875,6531,Port Sam,Australian Capital Territory,Australia
825,822,fulan 822,NaN,59,41 Jenkins KnollSuite 438,2588,Lake Andrewport,South Australia,Australia
859,855,fulan 855,NaN,55,603 O'keefe KnollSuite 782,8822,Port Dylanmouth,Tasmania,Australia
863,859,fulan 859,NaN,38,32 Isla GroveApt. 078,7711,Rosechester,New South Wales,Australia
914,909,fulan 909,NaN,62,976 Murray Station StApt. 036,3227,Langfort,Tasmania,Australia
934,929,fulan 929,NaN,68,394 Lily HillSuite 153,2353,Beahanfurt,Northern Territory,Australia
948,943,fulan 943,NaN,64,3117 Heller PlaceSuite 149,822,North Elijah,South Australia,Australia
952,946,fulan 946,NaN,24,8227 Nicholas HillSuite 150,115,South Jasper,Queensland,Australia
994,988,fulan 988,NaN,35,1130 Turner Estate DrSuite 925,9386,New Harry,Western Australia,Australia

Berdasarkan gambar di atas, dapat dilihat bahwa baris data tersebut masih mengandung banyak informasi penting sehingga sayang jika langsung dibuang. Oleh karena itu, pada kasus ini, kita akan menggunakan metode imputation untuk menangani missing value.

In [209]:
# Gunakanlah method value_counts()untuk mengidentifikasi nilai yang dominan.
customer_df.gender.value_counts()

gender
Prefer not to say    725
Male                 143
Female               115
Name: count, dtype: int64

Dominan data pada kategori gender yaitu Prefer not to say. Nilai inilah yang selanjutnya akan kita gunakan sebagai pengganti missing value. Proses penggantian ini dapat dilakukan menggunakan method fillna()

In [210]:
customer_df.fillna(value='Prefer not to say', inplace=True)

# cek apakah masih ada kolom data yang NaN
customer_df.isna().sum()

customer_id      0
customer_name    0
gender           0
age              0
home_address     0
zip_code         0
city             0
state            0
country          0
dtype: int64

#### Mencari inaccurate data

In [211]:
customer_df[customer_df.age == customer_df.age.max()]

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
967,961,fulan 961,Prefer not to say,700,29 Farrell ParadeSuite 818,6528,New Joseph,South Australia,Australia

kita bisa berasumsi bahwa inaccurate value tersebut terjadi karena human error sehingga kelebihan memasukkan nilai nol. Oleh karena itu, gantilah dengan nilai 70. Proses ini dilakukan dengan memanfaatkan method replace()

In [212]:
customer_df.replace({customer_df['age'].max(): 70}, inplace=True)

In [213]:
customer_df.describe()

       customer_id          age     zip_code
count  1001.000000  1001.000000  1001.000000
mean    500.312687    50.323676  5000.693307
std     289.265537    22.665946  2886.084454
min       1.000000    20.000000     2.000000
25%     250.000000    34.000000  2398.000000
50%     500.000000    50.000000  5079.000000
75%     751.000000    65.000000  7454.000000
max    1000.000000   500.000000  9998.000000

In [214]:
customer_df.replace({customer_df['age'].max(): 50}, inplace=True)

In [215]:
customer_df.describe()

       customer_id          age     zip_code
count  1001.000000  1001.000000  1001.000000
mean    499.863137    49.874126  5000.693307
std     289.615487    17.644663  2886.084454
min       1.000000    20.000000     2.000000
25%     249.000000    34.000000  2398.000000
50%     499.000000    50.000000  5079.000000
75%     751.000000    65.000000  7454.000000
max    1000.000000    80.000000  9998.000000

###Menilai Data orders_df

In [216]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   object
 4   delivery_date  1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [217]:
order_df.isna().sum()

order_id         0
customer_id      0
payment          0
order_date       0
delivery_date    0
dtype: int64

In [218]:
print("Jumlah duplikasi: ",order_df.duplicated().sum())
order_df.describe()

Jumlah duplikasi:  0

          order_id  customer_id       payment
count  1000.000000  1000.000000   1000.000000
mean    500.500000   506.640000  33972.936000
std     288.819436   277.115502  14451.609047
min       1.000000     1.000000  10043.000000
25%     250.750000   275.250000  21329.250000
50%     500.500000   515.000000  33697.500000
75%     750.250000   737.250000  46249.000000
max    1000.000000  1000.000000  59910.000000

Masalah yang ada pada **order_df**

*   Kolom order_date dan delivery_date menggunakan tipe data object / string, seharusnya datetime

### Membersihkan order_df

#### Mengganti tipe data dari Object menjadi datetime

Untuk mengatasi masalah ini, kita akan mengganti tipe data pada kolom order_date & delivery_date menjadi datetime. Proses ini dapat dilakukan menggunakan function to_datetime() yang disediakan oleh library pandas

In [219]:
datetime_columns = ["order_date", "delivery_date"]

for column in datetime_columns:
  order_df[column] = pd.to_datetime(order_df[column])

In [220]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   datetime64[ns]
 4   delivery_date  1000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3)
memory usage: 39.2 KB

### Menilai product_df

In [221]:
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266 entries, 0 to 1265
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1266 non-null   int64
 1   product_type  1266 non-null   object
 2   product_name  1266 non-null   object
 3   size          1266 non-null   object
 4   colour        1266 non-null   object
 5   price         1266 non-null   int64
 6   quantity      1266 non-null   int64
 7   description   1266 non-null   object
dtypes: int64(3), object(5)
memory usage: 79.2+ KB

In [222]:
print("Jumlah duplikasi: ",product_df.duplicated().sum())
product_df.describe()

Jumlah duplikasi:  6

        product_id        price     quantity
count  1266.000000  1266.000000  1266.000000
mean    627.926540   105.812006    60.138231
std     363.971586     9.715611    11.682791
min       0.000000    90.000000    40.000000
25%     313.250000    95.250000    50.000000
50%     626.500000   109.000000    60.000000
75%     942.750000   114.000000    70.000000
max    1259.000000   119.000000    80.000000

Masalah yang ada pada product_df

*  Terdapat 6 buah data yang terindikasi duplikasi

### Membersihkan product_df

#### Menghapus data yang duplikat / sama

In [223]:
product_df.drop_duplicates(inplace=True)

In [224]:
print("Jumlah duplikasi: ", product_df.duplicated().sum())

Jumlah duplikasi:  0

### Menilai Sales_df

In [225]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sales_id        5000 non-null   int64
 1   order_id        5000 non-null   int64
 2   product_id      5000 non-null   int64
 3   price_per_unit  5000 non-null   int64
 4   quantity        5000 non-null   int64
 5   total_price     4981 non-null   float64
dtypes: float64(1), int64(5)
memory usage: 234.5 KB

In [226]:
sales_df.isna().sum()

sales_id           0
order_id           0
product_id         0
price_per_unit     0
quantity           0
total_price       19
dtype: int64

In [227]:
print("Jumlah duplikasi: ",sales_df.duplicated().sum())
sales_df.describe()

Jumlah duplikasi:  0

,sales_id,order_id,product_id,price_per_unit,quantity,total_price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,4981.000000
mean,2499.500000,503.038200,634.053200,103.501600,1.99240,206.307368
std,1443.520003,285.964418,363.255794,9.195004,0.80751,86.352449
min,0.000000,1.000000,1.000000,90.000000,1.00000,90.000000
25%,1249.750000,258.000000,323.000000,95.000000,1.00000,112.000000
50%,2499.500000,504.500000,635.000000,102.000000,2.00000,204.000000
75%,3749.250000,749.000000,951.000000,112.000000,3.00000,285.000000
max,4999.000000,999.000000,1259.000000,119.000000,3.00000,357.000000

Masalah yang ada pada sales_df

*  19 data pada kolom total_price yang NULL / Kosong

### Membersihkan sales_df

#### Mengisi Missing Value

In [228]:
# Mencari data yang ada missing value
sales_df[sales_df.total_price.isna()]

      sales_id  order_id  product_id  price_per_unit  quantity  total_price
9            9         2        1196             105         1          NaN
121        121        27        1027              90         3          NaN
278        278        63         360              94         2          NaN
421        421        95        1091             115         1          NaN
489        489       108        1193             105         3          NaN
539        539       117         405             119         2          NaN
636        636       134         653              93         3          NaN
687        687       145        1138             102         1          NaN
854        854       177          64             104         1          NaN
1079      1079       222         908              94         3          NaN
1193      1193       248        1121             102         2          NaN
1313      1313       272         826             117         1          NaN
1548      1548       316         103             118         3          NaN
1688      1688       345         428             107         1          NaN
1775      1775       359         694             113         2          NaN
1902      1902       381        1218             105         3          NaN
2025      2025       408         611             112         3          NaN
2164      2164       436         583             100         3          NaN
2347      2347       476         696             113         2          NaN

In [229]:
# Filling missing value of total price with multiply price_per_unit and
sales_df["total_price"] = sales_df["price_per_unit"] * sales_df["quantity"]

In [230]:
# Checking if there is any missing value
sales_df.isna().sum()

sales_id          0
order_id          0
product_id        0
price_per_unit    0
quantity          0
total_price       0
dtype: int64

## Exploratory Data Analysis

Berdasarkan beberapa masalah tersebut, kita dapat mendefinisikan beberapa pertanyaan bisnis seperti berikut.

*  Bagaimana performa penjualan dan revenue perusahaan dalam beberapa bulan terakhir?
*  Produk apa yang paling banyak dan paling sedikit terjual?
*  Bagaimana demografi pelanggan yang kita miliki?
*  Kapan terakhir pelanggan melakukan transaksi?
*  Seberapa sering seorang pelanggan melakukan pembelian dalam beberapa bulan terakhir?
*  Berapa banyak uang yang dihabiskan pelanggan dalam beberapa bulan terakhir?

### Eksplorasi Data customer_df

In [231]:
customer_df.describe(include='all')

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
count,1001.000000,1001,1001,1001.000000,1001,1001.000000,1001,1001,1001
unique,NaN,1000,3,NaN,1000,NaN,961,8,1
top,NaN,fulan 943,Prefer not to say,NaN,3117 Heller PlaceSuite 149,NaN,New Ava,South Australia,Australia
freq,NaN,2,743,NaN,2,NaN,3,140,1001
mean,499.863137,NaN,NaN,49.874126,NaN,5000.693307,NaN,NaN,NaN
std,289.615487,NaN,NaN,17.644663,NaN,2886.084454,NaN,NaN,NaN
min,1.000000,NaN,NaN,20.000000,NaN,2.000000,NaN,NaN,NaN
25%,249.000000,NaN,NaN,34.000000,NaN,2398.000000,NaN,NaN,NaN
50%,499.000000,NaN,NaN,50.000000,NaN,5079.000000,NaN,NaN,NaN
75%,751.000000,NaN,NaN,65.000000,NaN,7454.000000,NaN,NaN,NaN
max,1000.000000,NaN,NaN,80.000000,NaN,9998.000000,NaN,NaN,NaN